### PR TITLE
Overhaul

### PR DESCRIPTION
**Pull request by TorHou**
Heyo @bgruening.
Let me know if you see something you don't like, I'll add more to this branch which reflect the changes I'm doing to the Galaxy configs.

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks @TorHou!

**Comment by bgruening** [comment]
@TorHou GATK should be put into a `deprecated` section if you ask me :) We are not maintaining it anymore and do not recommend it.

**Comment by bgruening** [comment]
@TorHou should we merge this?
I would like to add a few new tools and I'm not sure where to add without causing you troubles.

**Comment by TorHou** [comment]
go ahead. You can merge and modify at will :wink:

**Comment by bgruening** [comment]
Oki  doki.

**Pull request merged**
